### PR TITLE
Patch for BR preservation

### PR DESCRIPTION
**Pull request by gregziegan**
**Pre-merge checklist**
- [x] accompanying tests are written and passing
- [x] `npm run install` passes with no errors
- [x] `npm run lint` passes with no errors

**Description of changes**
BR is now preserved

**Reason for changes or related GitHub issue**
#21

@aem

### CODE REVIEW

**Comment by gregziegan** [comment]
When `npm install`ing my fork currently, the gulp build does not run the `gulp` script to build the `dist` directory. Any idea why that would be?

**Comment by aem** [comment]
I personally believe that build steps shouldn't slow down the installation process, so I don't run `gulp` as a part of a `prepublish` script, rather I just have a local alias for publishing to NPM that runs `gulp; npm publish`

**Comment by aem** [comment]
Can you possibly write a unit test that accompanies this change? It's a good catch and something that I don't want to regress

**Comment by gregziegan** [comment]
We're good to go 👍  It's a simple test but it does fail before my patch

**Comment by aem** [comment]
@thebritican looks solid! merging and will publish 0.1.6 in a bit

**Pull request merged**
