### PR TITLE
Traverse nested list items

### PR DESCRIPTION
**Pull request by LeZuse**
**Pre-merge checklist**
- [x] code has been tested in Node and all major browsers _WIP_
- [x] accompanying tests are written and passing
- [x] `npm install` passes with no errors
- [x] `npm run lint` passes with no errors

**Description of changes**
This is an initial attempt to parse nested lists. I haven't done much of refactoring as I need to use it quickly and the change is not that huge.

**Reason for changes or related GitHub issue**
https://github.com/aem/docs-soap/issues/2

@aem

### CODE REVIEW

**Comment by aem** [comment]
i'm ok to merge this despite the codecov checks, and after that I'm going to turn off the patch checks from codecov because they seem to be calculated poorly.

**Comment by aem** [comment]
@LeZuse let me know when you're satisfied with browser testing and i'll merge and publish a new version

**Comment by LeZuse** [comment]
@aem Just finished browser testing. Safari, Chrome, Firefox. I tried testing IE, but the access to html clipboard is a pain there.

**Comment by aem** [comment]
Alright, sounds good. At some point soon I'm planning on throwing together an example page that can be loaded in any browser for testing purposes, but haven't gotten around to it

**Pull request merged**
